# Makefile for GNU cflow library.	-*- Makefile -*-

# Copyright (C) 2005 Free Software Foundation, Inc.

## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2, or (at your option)
## any later version.

## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
## 02110-1301, USA.

noinst_LIBRARIES = libcflow.a
noinst_HEADERS = argcv.h
libcflow_a_SOURCES = argcv.c
libcflow_a_LIBADD = $(LIBOBJS) $(ALLOCA)
libcflow_a_DEPENDENCIES = $(libcflow_a_LIBADD)

BUILT_SOURCES =
EXTRA_DIST = Makefile.tmpl pin.c
MAINTAINERCLEANFILES =
MOSTLYCLEANFILES =
lib_OBJECTS = $(libcflow_a_OBJECTS)

# gnulib modules
